import mongoose, { Schema } from "mongoose";

const schema = new Schema({
  order: { type: Schema.Types.ObjectId, ref: "Order", required: true, unique: true, index: true },
  customer: { type: Schema.Types.ObjectId, ref: "User", required: true, index: true },
  storeAdmin: { type: Schema.Types.ObjectId, ref: "User", default: null, index: true },
  itemSubtotal: { type: Number, default: 0, min: 0 },
  discountAmount: { type: Number, default: 0, min: 0 },
  taxAmount: { type: Number, default: 0, min: 0 },
  deliveryFee: { type: Number, default: 0, min: 0 },
  platformFee: { type: Number, default: 0, min: 0 },
  otherFees: { type: Number, default: 0, min: 0 },
  customerPayable: { type: Number, default: 0, min: 0 },
  paymentMethod: { type: String, default: "" },
  paymentStatus: { type: String, default: "" },
  storeCommissionRate: { type: Number, default: 0, min: 0, max: 100 },
  platformCommissionRate: { type: Number, default: 0, min: 0, max: 100 },
  deliveryPayout: { type: Number, default: 0, min: 0 },
  deliveryPayoutRule: { type: String, default: "" },
  paymentGatewayFee: { type: Number, default: 0, min: 0 },
  taxOnPlatformFee: { type: Number, default: 0, min: 0 },
  storeGrossPayable: { type: Number, default: 0, min: 0 },
  storeDeductions: { type: Number, default: 0, min: 0 },
  storeNetPayable: { type: Number, default: 0, min: 0 },
  platformGrossEarning: { type: Number, default: 0, min: 0 },
  platformExpenses: { type: Number, default: 0, min: 0 },
  platformNetEarning: { type: Number, default: 0 },
  ownerShare: { type: Number, default: 0, min: 0 },
  ownerShareAmount: { type: Number, default: 0, min: 0 },
  currency: { type: String, default: "INR" },
  discountFunding: { type: String, enum: ["STORE_FUNDED", "PLATFORM_FUNDED", "SHARED_FUNDED", "UNSPECIFIED"], default: "UNSPECIFIED" },
  storeDiscountContribution: { type: Number, default: 0, min: 0 },
  platformDiscountContribution: { type: Number, default: 0, min: 0 },
  gatewayFeeBearer: { type: String, enum: ["PLATFORM", "STORE", "SHARED", "UNSPECIFIED"], default: "UNSPECIFIED" },
  sourceType: { type: String, default: "FRESHBASKET_DIRECT" },
  frozenAt: { type: Date, default: Date.now, index: true },
}, { timestamps: true });

export default mongoose.models.OrderFinancialSnapshot || mongoose.model("OrderFinancialSnapshot", schema);
